In [1]:

import numpy as np

In [16]:
1/2

0.5

In [7]:
np.arange(0,11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0,11,2)


array([ 0,  2,  4,  6,  8, 10])

In [54]:
np.random.randint(0,200,50)

array([129, 163,  88,   7, 157,  88,  12,  55, 186,  70, 189,  87,  99,
       122, 108,  20, 110, 118, 179,  78,   3,   7,  53,  89, 153,   1,
       155, 180, 146,  71, 178, 194, 132, 127,  72, 134,  89, 107, 181,
        18,  90,  84,  16,   9,  62,  71,  71,  61,  27, 163])

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones((5,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

---
# Random function


In [18]:
np.random.rand(5,5)

array([[ 0.55073248,  0.74201018,  0.03554989,  0.91759621,  0.31856215],
       [ 0.23218257,  0.7833043 ,  0.8341235 ,  0.3825243 ,  0.44152976],
       [ 0.34401571,  0.74468776,  0.23444641,  0.21199364,  0.59625802],
       [ 0.06365739,  0.58731969,  0.32495627,  0.6795069 ,  0.56312427],
       [ 0.53909827,  0.20085151,  0.83603387,  0.49290431,  0.85940168]])

In [17]:
np.random.randn(5,5)

array([[ 0.8180315 ,  1.43812212,  1.06694975,  0.05348294, -0.12724859],
       [ 0.13798267,  0.51123946,  2.29970241,  0.30566159, -0.34065754],
       [-0.62133601, -0.36955979, -1.21321668, -1.56132507,  1.11645067],
       [-1.16575763,  1.60254435,  0.22085173, -0.9712771 ,  0.6850297 ],
       [-1.31894035,  1.34786336, -0.57006179,  1.25988394, -0.16950655]])

In [19]:
np.random.randint(1,100)

25

In [20]:
np.random.randint(1,100,10)

array([ 5, 78, 21, 74, 88, 17, 31, 91, 16, 96])

In [21]:
arr = np.arange(0,25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr1 = np.random.randint(0,100,25)

In [24]:
arr1

array([73, 26, 43, 58, 93, 25,  1, 98, 46, 69, 15, 78, 69, 80, 35, 42, 48,
       71, 80, 35, 65, 37, 43, 62, 72])

# reshape function


In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr1.reshape(5,5)

array([[73, 26, 43, 58, 93],
       [25,  1, 98, 46, 69],
       [15, 78, 69, 80, 35],
       [42, 48, 71, 80, 35],
       [65, 37, 43, 62, 72]])

# Max & Min value of Array

In [30]:
arr1.max()

98

In [31]:
arr1.min()

1

# how to find location array


In [34]:
arr1 

array([62, 85, 70, 70, 47, 26, 94, 79, 89, 65,  2, 22, 92, 60, 74, 62, 44,
       64, 67, 91,  7, 81, 64, 51, 26])

In [35]:
arr1.argmax()

6

In [36]:
arr1.argmin()

10

In [37]:
arr1.shape

(25,)

In [38]:
arr1= arr1.reshape(5,5)

In [39]:
arr1

array([[62, 85, 70, 70, 47],
       [26, 94, 79, 89, 65],
       [ 2, 22, 92, 60, 74],
       [62, 44, 64, 67, 91],
       [ 7, 81, 64, 51, 26]])

In [40]:
arr1.shape

(5, 5)

In [41]:
arr1.dtype

dtype('int32')

In [46]:
np.random.randint(0,200,50)

array([168,  12,  23,  97, 127,  46,  11, 167,  73, 181, 102, 135,  12,
        38, 153,   4, 127,  15, 124,  26, 117,   8, 158, 114,  70, 141,
       115,  40, 110, 139,   0, 104, 128, 148,  54, 156, 142, 152, 139,
        75,  33,  23,  49,  97,  45,  97,  11, 116,  62, 124])

In [50]:
from numpy.random import randint

In [52]:
randint(0,200,90)

array([ 12,  99,  51, 193, 199, 108,  93, 153, 180, 116,  35,   5, 164,
        47, 178,  36,  68, 169,  68,  24, 120,  59, 103,  44, 171, 145,
         5,  35, 129, 163, 164,   1, 185,  76, 188,  99,  93,  24,  52,
        12,  52, 167, 197, 139, 182,  98,  51, 122, 194,  95, 174, 191,
       171, 143,   2, 146, 124, 187, 123, 146,  45, 170, 149, 111, 115,
       123,  14, 166, 181, 129,  20, 172, 148,  46,  56,   4, 193,  71,
        65,  31,  75,  57, 145, 146, 167, 118,  47, 196,  46, 147])

# Numpy indaxing and selection "slicing"

In [1]:
import numpy as np

In [3]:
 arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[1:4]

array([1, 2, 3])

In [6]:
arr[9]

9

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [11]:
arr[0:5]= 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [25]:
arr= np.arange(0,11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
slice_of_arr= arr[:6]

In [29]:
slice_of_arr[:]=22

In [30]:
slice_of_arr

array([22, 22, 22, 22, 22, 22])

In [33]:
arr

array([22, 22, 22, 22, 22, 22,  6,  7,  8,  9, 10])

In [31]:
arr_copy= arr.copy()

In [32]:
arr_copy

array([22, 22, 22, 22, 22, 22,  6,  7,  8,  9, 10])

In [34]:
arr_copy[:]=100

In [35]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [36]:
arr

array([22, 22, 22, 22, 22, 22,  6,  7,  8,  9, 10])

# numpy Matrix and slicing it


In [38]:
import numpy as np

In [39]:
arr1= np.array([[5,10,15],[20,25,30],[35,40,45]])

# Double brackets notation

In [40]:
arr1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr1[0]

array([ 5, 10, 15])

In [42]:
arr1[0][1]

10

In [43]:
arr1[1][2]

30

# single coma notation

In [44]:
arr1[0,1]

10

In [45]:
arr1[1,2]

30

In [49]:
#slicing matrix

In [48]:
arr1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
arr1[:2,1:]

array([[10, 15],
       [25, 30]])

In [51]:
arr1[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [53]:
arr1[1:,:2]

array([[20, 25],
       [35, 40]])

# Conditional selection

In [54]:
arr2= np.arange(0,11)

In [55]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
bool_arr2=arr2>5

In [58]:
bool_arr2

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [59]:
arr2[bool_arr2]

array([ 6,  7,  8,  9, 10])

In [60]:
arr2[arr2>5]

array([ 6,  7,  8,  9, 10])

In [62]:
arr2[arr2<6]

array([0, 1, 2, 3, 4, 5])

In [63]:
arr3= np.arange(50).reshape(5,10)

In [64]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [73]:
arr3[2:4,7:]

array([[27, 28, 29],
       [37, 38, 39]])

In [82]:
arr3[4,5]

45

In [74]:
arr3[3][1]

31

In [76]:
arr3[4:,4:]

array([[44, 45, 46, 47, 48, 49]])

In [83]:
arr3[2:4,5:8]

array([[25, 26, 27],
       [35, 36, 37]])

#  Numpy Operations:

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
arr -100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [9]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [10]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000], dtype=int32)

In [11]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [12]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [13]:
np.max(arr)

10

In [14]:
np.min(arr)

0

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [16]:
np.log(arr)

C:\Users\flang\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])